server:
  port: 8600
  servlet:
    session.persistent: false

spring:
  application:
    name: file-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000000000
      max-request-size: 10000000000
  data:
    mongodb.uri: 'mongodb://admin:123456@mongodb-server/devdb?authSource=admin'

website:
  app:
    id: 6
    password: 5pwgil3isg
    permissions:
      file:
        normal-upload: service
        '*': normal
  file.dir: D:/test/
logging:
  level:
    root: info
    org.apache.coyote.http11.Http11InputBuffer: debug
